---
version: '3.6'

services:
  db:
    image: postgres:14.3-alpine3.15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5

  app:
    container_name: coupon-app
    build: .
    image: coupon-app
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  ui:
    container_name: coupon-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: coupon-ui
    restart: unless-stopped
    environment:
      PUBLIC_API_URL: "http://coupon-app:8080"
    ports:
      - 5173:5173
    depends_on:
      - db
      - app
