version: "3.6"
services:
  frontend:
    container_name: coupon-ui
    image: coupon-ui
    build: .
    command: sh -c "npm run dev"  # comment out before installing svelte
    # command: /bin/sh
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    network_mode: "host"
