---
name: Lint UI
on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './ui/package-lock.json'

      - name: Setup dependencies
        run: npm ci

      - name: Run prettier and eslint
        run: npm run lint
